### PR TITLE
Update for Swift 3 and xCode 8

### PR DESCRIPTION
**Pull request by rudedogg**
This update changes the API a little bit, which I mentioned in `CHANGELOG.md`. Because this isn't backwards compatible I bumped the version of the podspec to `1.0.0`. 

The pod lint passes without warnings, and the examples appear to work well. Let me know what you think, or if you'd like me to make any changes.

Thanks!

### CODE REVIEW

**Comment by raspu** [comment]
Hi! Thanks for all the effort you put here :). I was hopping on closing #1  before moving to 1.0, but I don't think I will be able to do it any time soon. So, I will merge your changes :).

**Comment by raspu** [comment]
I'll make a new release this week.

**Comment by raspu** [comment]
@rudedogg Hey, I just sent you an invitation to become a collaborator. It would be nice if you can join as I have very little time to work on this project right now.

**Comment by rudedogg** [comment]
@raspu I'd love to. I'm doing some freelance work now, but I'd love to work on it in the near future, and can help with the admin stuff.

**Comment by raspu** [comment]
@rudedogg Thanks! I really appreciate it!

**Pull request merged**
