### PR TITLE
Add support for Swift 4.2, dependency injection, and highlight.js' ignoreIllegals option

### PR DESCRIPTION
**Pull request by kabiroberai**
Dependency injection allows one to use a custom highlight.min.js file instead of the one provided (eg. to add a custom language). Since the init parameters all have default values, this shouldn't be source-breaking.

### CODE REVIEW

**Comment by kabiroberai** [comment]
There are also two other areas that could do with improvement, but I didn’t change those since I thought you might have written them the way you did for a reason:

1. The language js files needn’t be included in the bundle — highlight.min.js already contains them
2. Using the JavaScriptCore `callMethod(_:withArguments:)` API would probably be faster and less error-prone than calling `jsContext.evaluateScript`, and additionally you wouldn’t need to escape the code string manually.

Do let me know whether I should add these changes to my PR :)

**Comment by raspu** [comment]
Hi @kabiroberai thank you for the PR! 

Everything looks in order, but let me take some time to test it. Also now that you are introducing a Shims file, I will move the rest of the shimming code there.

**Comment by kabiroberai** [comment]
As far as I can tell, the CSS files aren’t included in highlight.min.js. The primary use of dependency injection would be to add custom languages, as there's already a plethora of themes to choose from. That’s why the initialiser only allows you to customise the path to highlight.min.js (it always uses the framework bundle for themes)

**Comment by raspu** [comment]
I just confirmed that they are not included in the minified JS, but I also confirmed that there's no reference to them in the code itself and that they are found at run-time by the library. So you are right, it seems it's safe to introduce dependency injection, we just need to make sure that the JS file can always find the embedded CSSs. I was worried that maybe the list of themes was hard coded into the library, but it seems the library is more sophisticated than I thought. 

So if you are willing to include your proposed changes in this PR also, please go ahead, I will wait for you.

**Comment by kabiroberai** [comment]
Done; the PR should be ready to merge now

**Pull request merged**
